apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-istio-mult 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-istio-mult
  template:
    metadata:
      labels:
        app: grpc-istio-mult
    spec:
      containers:
        - name: local-mult-istio
          image: local/mult
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

